import { Router } from "express";
import { authRouter } from "./auth";
import { groupsRouter } from "./groups";
import { membersRouter } from "./members";
import { contributionsRouter } from "./contributions";
import { loansRouter } from "./loans";
import { notificationsRouter } from "./notifications";
import { auditRouter } from "./audit";
import { penaltiesRouter } from "./penalties";
import { reportsRouter } from "./reports";
import { adminsRouter } from "./admins";
import { passwordResetRouter } from "./passwordReset";
import { twoFactorRouter } from "./twoFactor";
import { sessionsRouter } from "./sessions";
import { dataExportRouter } from "./dataExport";
import { receiptRoutes } from "./receipts";
import { pushRoutes } from "./push";
import { distributionRoutes } from "./distributions";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/groups", groupsRouter);
apiRouter.use("/members", membersRouter);
apiRouter.use("/contributions", contributionsRouter);
apiRouter.use("/loans", loansRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/penalties", penaltiesRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/admins", adminsRouter);
apiRouter.use("/password-reset", passwordResetRouter);
apiRouter.use("/2fa", twoFactorRouter);
apiRouter.use("/sessions", sessionsRouter);
apiRouter.use("/export", dataExportRouter);
apiRouter.use("/receipts", receiptRoutes);
apiRouter.use("/push", pushRoutes);
apiRouter.use("/distributions", distributionRoutes);
